FOUNDATIONS: Retrieve Language By Id
hassanhabib/Sofee.Core pull request #66
Opened 2022-03-15 07:55 UTC by iCloudBMX

Closes #28

2022-03-15 14:22 UTC, hassanhabib commented on Sofee.Core.Api.Tests.Unit/Services/Foundations/Languages/LanguageServiceTests.Validation.RetrieveById.cs
> +                    Times.Once);
Push this line forward by one tab

2022-03-15 14:23 UTC, hassanhabib commented on Sofee.Core.Api.Tests.Unit/Services/Foundations/Languages/LanguageServiceTests.Validation.RetrieveById.cs
> +                    Times.Once);
Do the same for the rest.

2022-03-21 21:26 UTC, hassanhabib commented on Sofee.Core.Api/Services/Foundations/Languages/LanguageService.cs
> +            TryCatch(async () =>
@iCloudBMX it's not:

![image](https://user-images.githubusercontent.com/1453985/159366538-8c4dbd6c-31fd-4e4f-85ea-7223bd431e68.png)

2022-03-22 14:11 UTC, iCloudBMX commented on Sofee.Core.Api/Services/Foundations/Languages/LanguageService.cs
> +            TryCatch(async () =>
done

2022-03-23 01:02 UTC, ShriHumrudha requested changes

2022-03-23 01:02 UTC, ShriHumrudha commented on Sofee.Core.Api.Tests.Unit/Services/Foundations/Languages/LanguageServiceTests.Validation.RetrieveById.cs
> +            Language? noLanguage = null;
Why ?

2022-03-23 01:02 UTC, ShriHumrudha commented on Sofee.Core.Api/Models/Languages/Exceptions/NotFoundLanguageException.cs
> +﻿using System;
Copyrights

2022-03-23 20:24 UTC, iCloudBMX commented on Sofee.Core.Api.Tests.Unit/Services/Foundations/Languages/LanguageServiceTests.Validation.RetrieveById.cs
> +            Language? noLanguage = null;
done

2022-03-23 20:24 UTC, iCloudBMX commented on Sofee.Core.Api/Models/Languages/Exceptions/NotFoundLanguageException.cs
> +﻿using System;
done

2022-03-23 20:35 UTC, ShriHumrudha approved these changes

2022-05-30 00:33 UTC, merged