FOUNDATIONS: Language RetrieveAll
hassanhabib/Sofee.Core pull request #67
Opened 2022-03-16 18:24 UTC by KFitz114

2022-03-16 20:36 UTC, iCloudBMX commented on Sofee.Core.Api.Tests.Unit/Services/Foundations/Languages/LanguageServiceTests.RetrieveAll.Logic.cs
> +            this.loggingBrokerMock.VerifyNoOtherCalls();
you tested loggingBrokerMock twice, use storageBrokerMock instead of first loggingBrokerMock

2022-03-16 20:38 UTC, ShriHumrudha requested changes
We need to handled exceptions. You can move the PR to draft state if you are still working on it.

2022-03-16 20:38 UTC, ShriHumrudha commented on Sofee.Core.Api.Tests.Unit/Services/Foundations/Languages/LanguageServiceTests.RetrieveAll.Logic.cs
> +﻿using FluentAssertions;
Add copyrights header
Run code cleanup

2022-03-16 20:38 UTC, ShriHumrudha commented on Sofee.Core.Api.Tests.Unit/Services/Foundations/Languages/LanguageServiceTests.RetrieveAll.Logic.cs
> +            IQueryable<Language> expectedLanguages = randomLanguages.DeepClone();
Do we need DeepClone?

2022-03-16 20:38 UTC, ShriHumrudha commented on Sofee.Core.Api.Tests.Unit/Services/Foundations/Languages/LanguageServiceTests.cs
> +        private static IQueryable<Language> CreateRandomLanguages() =>
As it is spanning multiple line you can scope it.

2022-03-16 20:38 UTC, ShriHumrudha commented on Sofee.Core.Api/Services/Foundations/Languages/ILanguageService.cs
> +
Remove extra line

2022-05-05 05:16 UTC, ElbekDeveloper commented
@Mehdi-Aghaei  @KFitz114 this PR has long not been updated and comments have not been resolved. We might have to close this PR without merging due to inactivity.

2022-05-30 00:33 UTC, closed without merging